### ISSUE TITLE
Location not being pushed to tracker.transistorsoft.com

### ISSUE THREAD

**Issue by arianitu** [transistorsoft/cordova-background-geolocation-SampleApp#118]
Error is:

```
⚠️-[TSHttpService doPost:] HTTP ERROR: 500
***
* {"error":"Something failed!"}

2019-11-18 11:48:15.877892-0500 BG Geo[7106:573426] ⚠️-[TSHttpService doPost:] HTTP ERROR: 500
***
* {"error":"Something failed!"}
✅-[TSHttpService post:error:] UNL
```

**Comment by christocracy** [comment]
- What is your username?
- Have you modified the code?

**Comment by arianitu** [comment]
1. Username is: `smartapp-geo-test`
2. I have not modified the code and similar behaviour is happening for a few other people who are trying the app. They can't get the visualizer tool to work by clicking "View Server" and I assume it's because the server is responding with that 500 error.

Another person at the org is using Android and downloaded directly from the app store, I just built it from github, no changes done at all.

**Comment by arianitu** [comment]
@christocracy maybe we should setup our own server, but I don't think they can change the URL on their end if they download directly from the Android store.

Are you seeing the same issue as us?

**Comment by christocracy** [comment]
There's a lot of work going on with the demo server currently.  @Sigura ?

**Comment by christocracy** [comment]
Can you hit the server right now while I'm tailing the logs?

**Comment by Sigura** [comment]
I did, console map show my position right immediately.

**Comment by christocracy** [comment]
I have no issues either.  Only invalid device config can cause this.

**Comment by arianitu** [comment]
@christocracy I did not make any changes to the github repo at all. I just did a `git clone` and ran the prepare commands and ran it on my iOS device. No data shows.

I had two other people at the organization download the app directly from the Android store and they get the same results.

Is there something we are doing wrong? 

1. We click on Simple Map
2. We click the Toggle on the top right to enable it
3. We click on the Play button on the bottom right 
4. We record some data and then hit the red Pause button
5. We click the Sync Button and confirm syncing of 37+ points
6. We visit http://tracker.transistorsoft.com/smartapp-geo-test

I notice in my Console when running the Developer Tools, I get a Error 500 from the server, but I didn't actually do or change anything to the github repo. 

I can try to clone again and do a rebuild

**Comment by christocracy** [comment]
Try *Advanced App*.

**Comment by christocracy** [comment]
@Sigura 
```
2019-11-19T15:21:28.748557+00:00 app[web.1]: POST /locations/smartapp-geo-test
2019-11-19T15:21:28.748578+00:00 app[web.1]: {
2019-11-19T15:21:28.748581+00:00 app[web.1]: "host": "tracker.transistorsoft.com",
2019-11-19T15:21:28.748583+00:00 app[web.1]: "connection": "close",
2019-11-19T15:21:28.748585+00:00 app[web.1]: "content-type": "application/json",
2019-11-19T15:21:28.748587+00:00 app[web.1]: "accept": "*/*",
2019-11-19T15:21:28.748589+00:00 app[web.1]: "user-agent": "BG%20Geo/3.3.0 CFNetwork/1120 Darwin/19.0.0",
2019-11-19T15:21:28.748591+00:00 app[web.1]: "accept-language": "en-ca",
2019-11-19T15:21:28.748593+00:00 app[web.1]: "accept-encoding": "gzip, deflate",
2019-11-19T15:21:28.748595+00:00 app[web.1]: "x-request-id": "98fa4010-f2a6-43c4-89da-472c2f612a19",
2019-11-19T15:21:28.748597+00:00 app[web.1]: "x-forwarded-for": "192.222.152.162",
2019-11-19T15:21:28.748599+00:00 app[web.1]: "x-forwarded-proto": "http",
2019-11-19T15:21:28.748601+00:00 app[web.1]: "x-forwarded-port": "80",
2019-11-19T15:21:28.748603+00:00 app[web.1]: "via": "1.1 vegur",
2019-11-19T15:21:28.748605+00:00 app[web.1]: "connect-time": "4",
2019-11-19T15:21:28.748607+00:00 app[web.1]: "x-request-start": "1574176888739",
2019-11-19T15:21:28.748609+00:00 app[web.1]: "total-route-time": "0",
2019-11-19T15:21:28.748611+00:00 app[web.1]: "content-length": "561"
2019-11-19T15:21:28.748614+00:00 app[web.1]: }
2019-11-19T15:21:28.748623+00:00 app[web.1]: Authorization: undefined
2019-11-19T15:21:28.748723+00:00 app[web.1]: {
2019-11-19T15:21:28.748726+00:00 app[web.1]: "location": {
2019-11-19T15:21:28.748728+00:00 app[web.1]: "coords": {
2019-11-19T15:21:28.748730+00:00 app[web.1]: "speed": -1,
2019-11-19T15:21:28.748733+00:00 app[web.1]: "longitude": -73.57098433339597,
2019-11-19T15:21:28.748735+00:00 app[web.1]: "floor": null,
2019-11-19T15:21:28.748741+00:00 app[web.1]: "latitude": 45.49671199275226,
2019-11-19T15:21:28.748743+00:00 app[web.1]: "accuracy": 65,
2019-11-19T15:21:28.748745+00:00 app[web.1]: "altitude_accuracy": 10,
2019-11-19T15:21:28.748747+00:00 app[web.1]: "altitude": 42,
2019-11-19T15:21:28.748749+00:00 app[web.1]: "heading": -1
2019-11-19T15:21:28.748751+00:00 app[web.1]: },
2019-11-19T15:21:28.748753+00:00 app[web.1]: "extras": {},
2019-11-19T15:21:28.748755+00:00 app[web.1]: "is_moving": false,
2019-11-19T15:21:28.748757+00:00 app[web.1]: "event": "motionchange",
2019-11-19T15:21:28.748759+00:00 app[web.1]: "odometer": 0,
2019-11-19T15:21:28.748761+00:00 app[web.1]: "uuid": "A769C125-41AE-4923-824F-86402E3B76CC",
2019-11-19T15:21:28.748764+00:00 app[web.1]: "activity": {
2019-11-19T15:21:28.748766+00:00 app[web.1]: "type": "still",
2019-11-19T15:21:28.748768+00:00 app[web.1]: "confidence": 100
2019-11-19T15:21:28.748769+00:00 app[web.1]: },
2019-11-19T15:21:28.748771+00:00 app[web.1]: "battery": {
2019-11-19T15:21:28.748773+00:00 app[web.1]: "level": 0.47999998927116394,
2019-11-19T15:21:28.748775+00:00 app[web.1]: "is_charging": true
2019-11-19T15:21:28.748777+00:00 app[web.1]: },
2019-11-19T15:21:28.748779+00:00 app[web.1]: "timestamp": "2019-11-18T16:42:18.944Z"
2019-11-19T15:21:28.748781+00:00 app[web.1]: },
2019-11-19T15:21:28.748783+00:00 app[web.1]: "device": {
2019-11-19T15:21:28.748785+00:00 app[web.1]: "uuid": "iPhone11-6",
2019-11-19T15:21:28.748787+00:00 app[web.1]: "version": "13.2.2",
2019-11-19T15:21:28.748810+00:00 app[web.1]: "model": "iPhone11,6",
2019-11-19T15:21:28.748813+00:00 app[web.1]: "manufacturer": "Apple",
2019-11-19T15:21:28.748814+00:00 app[web.1]: "framework": "Cordova",
2019-11-19T15:21:28.748817+00:00 app[web.1]: "platform": "iOS"
2019-11-19T15:21:28.748818+00:00 app[web.1]: },
2019-11-19T15:21:28.748820+00:00 app[web.1]: "company_token": "smartapp-geo-test"
2019-11-19T15:21:28.748822+00:00 app[web.1]: }
2019-11-19T15:21:28.748824+00:00 app[web.1]:
2019-11-19T15:21:28.750193+00:00 app[web.1]: Executing (8fcc4952-9fd4-4fd4-bc2f-3862c6b24ec6): START TRANSACTION;
2019-11-19T15:21:28.763109+00:00 app[web.1]: Executing (8fcc4952-9fd4-4fd4-bc2f-3862c6b24ec6): SELECT "id", "company_token", "created_at" FROM "companies" AS "companies" WHERE "companies"."company_token" = 'smartapp-geo-test' LIMIT 1;
2019-11-19T15:21:28.776623+00:00 app[web.1]: Executing (8fcc4952-9fd4-4fd4-bc2f-3862c6b24ec6): CREATE OR REPLACE FUNCTION pg_temp.testfunc(OUT response "companies", OUT sequelize_caught_exception text) RETURNS RECORD AS $func_e8dd5db978a24083a1e77de86727bca8$ BEGIN INSERT INTO "companies" ("id","company_token","created_at") VALUES (DEFAULT,'smartapp-geo-test','2019-11-19 15:21:28.748 +00:00') RETURNING * INTO response; EXCEPTION WHEN unique_violation THEN GET STACKED DIAGNOSTICS sequelize_caught_exception = PG_EXCEPTION_DETAIL; END $func_e8dd5db978a24083a1e77de86727bca8$ LANGUAGE plpgsql; SELECT (testfunc.response).*, testfunc.sequelize_caught_exception FROM pg_temp.testfunc(); DROP FUNCTION IF EXISTS pg_temp.testfunc();
2019-11-19T15:21:28.789124+00:00 app[web.1]: Executing (8fcc4952-9fd4-4fd4-bc2f-3862c6b24ec6): COMMIT;
2019-11-19T15:21:28.797298+00:00 app[web.1]: err:  { SequelizeDatabaseError: permission denied for sequence companies_id_seq
2019-11-19T15:21:28.797310+00:00 app[web.1]: at Query.formatError (/app/node_modules/sequelize/lib/dialects/postgres/query.js:366:16)
2019-11-19T15:21:28.797313+00:00 app[web.1]: at query.catch.err (/app/node_modules/sequelize/lib/dialects/postgres/query.js:72:18)
2019-11-19T15:21:28.797315+00:00 app[web.1]: at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
2019-11-19T15:21:28.797318+00:00 app[web.1]: at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
2019-11-19T15:21:28.797320+00:00 app[web.1]: at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
2019-11-19T15:21:28.797323+00:00 app[web.1]: at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
2019-11-19T15:21:28.797324+00:00 app[web.1]: at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:725:18)
2019-11-19T15:21:28.797327+00:00 app[web.1]: at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
2019-11-19T15:21:28.797329+00:00 app[web.1]: at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
2019-11-19T15:21:28.797331+00:00 app[web.1]: at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
2019-11-19T15:21:28.797333+00:00 app[web.1]: at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:15:14)
2019-11-19T15:21:28.797336+00:00 app[web.1]: at runCallback (timers.js:810:20)
2019-11-19T15:21:28.797341+00:00 app[web.1]: at tryOnImmediate (timers.js:768:5)
2019-11-19T15:21:28.797344+00:00 app[web.1]: at processImmediate [as _immediateCallback] (timers.js:745:5)
2019-11-19T15:21:28.797346+00:00 app[web.1]: name: 'SequelizeDatabaseError',
2019-11-19T15:21:28.797348+00:00 app[web.1]: parent:
2019-11-19T15:21:28.797351+00:00 app[web.1]: { error: permission denied for sequence companies_id_seq
2019-11-19T15:21:28.797353+00:00 app[web.1]: at Connection.parseE (/app/node_modules/pg/lib/connection.js:554:11)
2019-11-19T15:21:28.797355+00:00 app[web.1]: at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:381:17)
2019-11-19T15:21:28.797357+00:00 app[web.1]: at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:117:22)
2019-11-19T15:21:28.797359+00:00 app[web.1]: at emitOne (events.js:116:13)
2019-11-19T15:21:28.797362+00:00 app[web.1]: at Socket.emit (events.js:211:7)
2019-11-19T15:21:28.797364+00:00 app[web.1]: at addChunk (_stream_readable.js:263:12)
2019-11-19T15:21:28.797366+00:00 app[web.1]: at readableAddChunk (_stream_readable.js:250:11)
2019-11-19T15:21:28.797368+00:00 app[web.1]: at Socket.Readable.push (_stream_readable.js:208:10)
2019-11-19T15:21:28.797370+00:00 app[web.1]: at TCP.onread (net.js:601:20)
2019-11-19T15:21:28.797372+00:00 app[web.1]: name: 'error',
2019-11-19T15:21:28.797376+00:00 app[web.1]: length: 332,
2019-11-19T15:21:28.797377+00:00 app[web.1]: severity: 'ERROR',
2019-11-19T15:21:28.797379+00:00 app[web.1]: code: '42501',
2019-11-19T15:21:28.797381+00:00 app[web.1]: detail: undefined,
2019-11-19T15:21:28.797383+00:00 app[web.1]: hint: undefined,
2019-11-19T15:21:28.797385+00:00 app[web.1]: position: undefined,
2019-11-19T15:21:28.797387+00:00 app[web.1]: internalPosition: undefined,
2019-11-19T15:21:28.797389+00:00 app[web.1]: internalQuery: undefined,
2019-11-19T15:21:28.797396+00:00 app[web.1]: where: 'SQL statement "INSERT INTO "companies" ("id","company_token","created_at") VALUES (DEFAULT,\'smartapp-geo-test\',\'2019-11-19 15:21:28.748 +00:00\') RETURNING *"\nPL/pgSQL function pg_temp_3.testfunc() line 1 at SQL statement',
2019-11-19T15:21:28.797398+00:00 app[web.1]: schema: undefined,
2019-11-19T15:21:28.797400+00:00 app[web.1]: table: undefined,
2019-11-19T15:21:28.797402+00:00 app[web.1]: column: undefined,

2019-11-19T15:21:28.797404+00:00 app[web.1]: dataType: undefined,
2019-11-19T15:21:28.797406+00:00 app[web.1]: constraint: undefined,
2019-11-19T15:21:28.797408+00:00 app[web.1]: file: 'sequence.c',
2019-11-19T15:21:28.797411+00:00 app[web.1]: line: '562',
2019-11-19T15:21:28.797413+00:00 app[web.1]: routine: 'nextval_internal',
```

**Comment by arianitu** [comment]
@christocracy if you could remove my IP and my location from the above error message, that'd be great!

I know you can delete them from the website, but I just don't want it indexed on github

thank you!

**Comment by christocracy** [comment]
Try again.

**Comment by arianitu** [comment]
Amazing, works now. Thank you @christocracy
