### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by lei-xiaoming** [transistorsoft/cordova-background-geolocation-SampleApp#135]
My execution environment is below,
$ node -v
v16.13.1
$ cordova -v
 11.0.0

./cordova-background-geolocation-SampleApp
$npm install. An error has occurred. If you know anything, please help.

```
npm ERR! code 1
npm ERR! path C:\work\test\cordova-background-geolocation-SampleApp\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\work\test\cordova-background-geolocation-SampleApp\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\work\\test\\cordova-background-geolocation-SampleApp\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\work\test\cordova-background-geolocation-SampleApp\node_modules\node-gyp\node_modules\which\which.js:13:12)  npm Enpm ERR! gyp verb `which` failed     at getNotFoundError (C:\work\test\cordova-background-geolocation-SampleApp\node_modules\node-gyp\node_modules\which\which.js:13:12)       
npm ERR! gyp verb `which` failed     at F (C:\work\test\cordova-background-geolocation-SampleApp\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\work\test\cordova-background-geolocation-SampleApp\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\work\test\cordova-background-geolocation-SampleApp\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\work\test\cordova-background-geolocation-SampleApp\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\work\test\cordova-background-geolocation-SampleApp\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\work\test\cordova-background-geolocation-SampleApp\node_modules\node-gyp\node_modules\which\which.js:13:12)       npm ERR! gyp verb `which` failed     at F (C:\work\test\cordova-background-geolocation-SampleApp\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\work\test\cordova-background-geolocation-SampleApp\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\work\test\cordova-background-geolocation-SampleApp\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\work\test\cordova-background-geolocation-SampleApp\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\work\test\cordova-background-geolocation-SampleApp\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python39\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\work\\test\\cordova-background-geolocation-SampleApp\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\work\test\cordova-background-geolocation-SampleApp\node_modules\node-sassnpm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not oknpm ERR! Build failed with error code: 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\test\AppData\Local\npm-cache\_logs\2022-06-29T02_07_18_747Z-debug.log
```

**Comment by lei-xiaoming** [comment]
After updating from jdk1.8 to jdk11, the issue was resolved.

**Comment by cafrie** [comment]
> After updating from jdk1.8 to jdk11, the issue was resolved.

I have the exact same error.
@lei-xiaoming How did you update from jdk1.8 to jdk11?
